services:
  hlds-gameserver:
    build:
      context: .
      args:
        MOD: valve
    env_file: .env
    ulimits: # Truncated core dumps fix
      core:
        soft: 1073741824 # 1GB
        hard: 1073741824 # 1GB
    ports:
      - $PORT:27015/udp
    expose:
      - $PORT/udp
    stdin_open: true
    tty: true
    entrypoint: "./hlds_run"
    command: ["\
        -debug \
        -game valve \
        +ip 0.0.0.0 \
        +map $MAP \
        -maxplayers $MAXPLAYERS \
        +sv_lan $SV_LAN \
        +rcon_password \"$RCON_PASSWORD\" \
        +hostname \"$SERVER_NAME\"\
      "]

